Sticky footer [FOGL-2506]
foglamp/foglamp-gui pull request #396
Opened 2019-02-21 07:52 UTC by monika-Dianomic

2019-02-21 09:29 UTC, praveen-garg requested changes
<img width="515" alt="screenshot 2019-02-21 at 2 10 08 pm" src="https://user-images.githubusercontent.com/1974003/53158161-ff18a200-35e8-11e9-8077-31c7abda88a2.png">

why the version label is missing which we added recently?
why these blue dropdown icon appears on top of footer instead of getting hidden behind?
can we make copyright+ version stuff center of main container, instead of whole viewport.

2019-02-21 09:29 UTC, praveen-garg commented on src/app/components/layout/footer/footer.component.css
> +    padding: 2rem 1.5rem 2rem !important;
can we make it `1rem 1.5rem 1rem !important;`?

2019-02-21 11:41 UTC, praveen-garg requested changes

2019-02-21 11:41 UTC, praveen-garg commented on src/app/app.component.css
> +  padding-bottom: 120px;
why this padding added? and in px?!

2019-02-21 11:41 UTC, praveen-garg commented on src/app/components/layout/footer/footer.component.css
> +    height: 120px;
why this height added? and in px?!

2019-02-22 09:15 UTC, mshariq-nerd commented
LGTM! other then  pending `copyright+ version stuff center of main container, instead of whole viewport`

2020-01-15 09:55 UTC, monika-Dianomic commented
Closing in favour of [https://github.com/foglamp/foglamp-gui/pull/564](https://github.com/foglamp/foglamp-gui/pull/564)

2020-01-15 09:55 UTC, closed without merging