FOGL-3083: Update to Angular v8
foglamp/foglamp-gui pull request #493
Opened 2019-08-08 13:05 UTC by mshariq-nerd

2019-08-09 06:21 UTC, MonikaSharma06 reviewed
Please update `developers-guide` also.

2019-08-09 09:37 UTC, praveen-garg requested changes

2019-08-09 09:37 UTC, praveen-garg commented on .browserslistrc
> +last 1 FirefoxAndroid versions
Remove please.

2019-08-09 09:37 UTC, praveen-garg commented on .browserslistrc
> +Safari >= 11
What about iOS?

2019-08-09 09:37 UTC, praveen-garg commented on .browserslistrc
> +# Browsers that we support
should we remove browsers targets from .babelrc ?

2019-08-09 09:37 UTC, praveen-garg commented on src/polyfills.ts
> +// import 'core-js/es7/reflect';
why these have been commented. should we remove?

2019-09-17 10:24 UTC, mshariq-nerd commented
1. README and developers-guide 
   >Done

2. e2e 
   >Working
3. build size info current develop vs this
   > No change `INFO:  Deployable dist size   6.7M	dist`  on both branch
4. change-logs if any needed 
   > Updated

5. Removed `rxjs-compat` and `babel` dependencies 

6. App will now be more performant, thanks to differential loading. two bundles are created when building for production: a bundle for modern browsers that support ES6  and a bundle for older browsers that only support the ES5 version of JavaScript. **We are creating only one build as we are supporting ES6 compatible browsers only**

7. Import syntax changed for lazy loading routes. Those are more dynamic now like 
`{
    path: 'south', loadChildren: () => import('./components/core/south/south.module')
      .then(m => m.SouthModule)
  }`

2019-09-17 10:36 UTC, praveen-garg submitted a review, later dismissed

2019-09-17 10:37 UTC, MonikaSharma06 submitted a review, later dismissed

2019-09-17 10:37 UTC, praveen-garg commented on docs/changelog.md
> +## v1.x.x [xxxx-xx-xx]
v1.7.0next [2019-xx-xx]

2019-09-17 10:40 UTC, praveen-garg commented on docs/changelog.md
> +
also add, 
`Fixed notification service install and enabled check to get latest state`

>under Fixed

2019-09-17 11:18 UTC, praveen-garg approved these changes

2019-09-17 11:18 UTC, merged