FOGL-3029:  support for configuration item validity
foglamp/foglamp-gui pull request #518
Opened 2019-09-20 11:04 UTC by mshariq-nerd

2019-09-20 16:30 UTC, praveen-garg approved these changes

2019-09-22 17:29 UTC, praveen-garg requested changes
[demo.json.zip](https://github.com/foglamp/foglamp-gui/files/3640003/demo.json.zip)

<img width="1073" alt="Screenshot 2019-09-22 at 10 57 14 PM" src="https://user-images.githubusercontent.com/1974003/65391927-8a7b3100-dd8c-11e9-954b-98b98d66525e.png">

`demo1` should always be editable. but that is always non-editable!

also try `validity=""`

2019-09-22 17:49 UTC, praveen-garg commented on src/app/components/core/configuration-manager/view-config-item/view-config-item.component.ts
> +              data[k].eval = data[k].eval.includes(element.key) ? data[k].eval
Looks like we are setting  .eval (better to rename it - validatityExpression) to all config items, i.e. even if none than empty string?!

2019-09-22 17:49 UTC, praveen-garg commented on src/app/components/core/configuration-manager/view-config-item/view-config-item.component.ts
> +            try {
better to put try/catch thing inside if block `if (data[k]['validity'].trim() != "")`

2019-09-22 19:32 UTC, praveen-garg commented on src/app/components/core/configuration-manager/view-config-item/view-config-item.component.ts
> +              data[k].editable = eval(data[k].eval);
May be better `eval(data[k].validatityExpression) === false ? false : true` in-case of validatityExpression is incomplete e.g. "validity": "authentication" 

```
authetication="Yes"
eval("authetication")
"Yes"
```

2019-09-23 07:22 UTC, praveen-garg submitted a review, later dismissed

2019-09-23 12:43 UTC, praveen-garg submitted a review, later dismissed

2019-09-24 11:35 UTC, monika-Dianomic commented on src/app/components/core/configuration-manager/view-config-item/view-config-item.component.ts
> +                  console.log('Validity expression', data[k].validityExpression, 'for', k, 'evlauted to non-boolean value ', e);
Is there any need to log this?

2019-09-24 11:45 UTC, MonikaSharma06 submitted a review, later dismissed

2019-09-24 15:17 UTC, praveen-garg requested changes
validation error does not stop form to save!

2019-09-24 15:17 UTC, praveen-garg commented on src/app/components/core/configuration-manager/view-config-item/view-config-item.component.ts
> +                  console.log('Validity expression', data[k].validityExpression, 'for', k, 'evlauted to non-boolean value ', e);
make `data[k].validityExpression` -> `data[k].validity` to log origin expression 

typo `evlauted` -> `evaluated`

also remove the space after `... non-boolean value ` and before e value

2019-09-26 12:17 UTC, MonikaSharma06 submitted a review, later dismissed

2019-09-26 12:28 UTC, praveen-garg approved these changes

2019-09-26 12:29 UTC, merged