FOGL-3015: Fixed when time passes 00:00:00, graphs breaks
foglamp/foglamp-gui pull request #527
Opened 2019-10-04 11:35 UTC by mshariq-nerd

2019-10-07 10:12 UTC, mshariq-nerd commented
In case of multiple resources `severity` level not respected.
http://localhost:8081/foglamp/audit?source=CONCH&severity=SUCCESS
**Response** 
`{
audit: [ ],
totalCount: 0
}`

http://localhost:8081/foglamp/audit?source=CONCH,CONAD,SCHCH&severity=SUCCESS
```javascript
**Response** 
{
audit: [
{
timestamp: "2019-10-07 08:31:57.089",
details: {
category: "deliveryDemo",
items: {
enable: {
oldValue: "false",
newValue: "true"
},
asset: {
oldValue: "event",
newValue: "event11"
}
}
},
source: "CONCH",
**severity: "INFORMATION"**
},
{
timestamp: "2019-10-07 08:31:57.087",
details: {
category: "ruleDemo",
items: {
condition: {
oldValue: "<",
newValue: "<="
}
}
},
source: "CONCH",
severity: "INFORMATION"
}
],
totalCount: 47
}
```
In response `severity: "INFORMATION"`  not matching with the severity param passed in api endpoint.

2019-10-07 11:54 UTC, praveen-garg approved these changes

2019-10-07 12:52 UTC, praveen-garg requested changes

2019-10-07 12:52 UTC, praveen-garg commented on src/app/components/core/asset-readings/readings-graph/readings-graph.component.ts
> -    this.timestamps = readings.map((r: any) => datePipe.transform(r.timestamp, 'HH:mm:ss:SSS'));
Pass YY MM dd to respect the date

2019-10-07 12:52 UTC, praveen-garg commented on src/app/components/core/asset-readings/readings-graph/readings-graph.component.ts
> -            parser: 'HH:mm:ss',
Revert

2019-10-09 07:57 UTC, praveen-garg approved these changes

2019-10-09 08:12 UTC, merged