[FOGL-3585]: Allow to upload .cert, .cer, .crt, .json, .pem certificate file without key file
foglamp/foglamp-gui pull request #561
Opened 2020-01-02 09:15 UTC by monika-Dianomic

2020-01-02 11:11 UTC, shariq1501 requested changes

2020-01-02 11:11 UTC, mshariq-nerd commented on src/app/components/core/certificate/upload-certificate/upload-certificate.component.ts
> +      if (ext === 'cert' || ext === 'cer' || ext === 'crt' || ext === 'pem' || ext === 'json') {
This if condition can be changed like below to make code more readable. 
```const certExtensions = ['cert', 'cer', 'crt', 'pem', 'json'];
this.certExtension = false;
if (certExtensions.includes(ext)) {
this.certExtension = true;
}

2020-01-06 09:10 UTC, praveen-garg approved these changes

2020-01-06 09:19 UTC, shariq1501 approved these changes

2020-01-06 10:06 UTC, merged